#!/usr/bin/env python3
"""Generate a long, smooth rough-terrain track for high-speed validation."""

from __future__ import annotations

import json
import math
import struct
import zlib
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIRECTORY = ROOT / "models" / "upkie" / "high_speed"
LENGTH_M = 600.0
WIDTH_M = 6.0
NX = 6001
NY = 61
AMPLITUDE_M = 0.030
SEED = 8080


def _smooth_noise(
    rng: np.random.Generator,
    sample_count: int,
    sigma_samples: float,
) -> np.ndarray:
    radius = round(4.0 * sigma_samples)
    positions = np.arange(-radius, radius + 1)
    kernel = np.exp(-0.5 * (positions / sigma_samples) ** 2)
    kernel /= np.sum(kernel)
    noise = rng.normal(size=sample_count + 2 * radius)
    filtered = np.convolve(noise, kernel, mode="same")[radius:-radius]
    filtered -= np.mean(filtered)
    filtered /= np.max(np.abs(filtered))
    return filtered


def generate_heightfield() -> tuple[np.ndarray, dict[str, float]]:
    rng = np.random.default_rng(SEED)
    x = np.linspace(-LENGTH_M / 2.0, LENGTH_M / 2.0, NX)
    y = np.linspace(-WIDTH_M / 2.0, WIDTH_M / 2.0, NY)
    dx = float(x[1] - x[0])
    base = 0.014 * _smooth_noise(rng, NX, 10.0 / dx)

    # Long rounded crests remain meaningful at high speed without becoming
    # step impacts whose acceleration tends toward an impulse.
    for center in np.linspace(-240.0, 240.0, 28):
        shifted_center = center + rng.uniform(-3.0, 3.0)
        height = rng.uniform(-0.016, 0.026)
        width = rng.uniform(5.0, 12.0)
        base += height * np.exp(-0.5 * ((x - shifted_center) / width) ** 2)

    envelope = np.ones_like(x)
    envelope[x < -275.0] = 0.0
    transition = (x >= -275.0) & (x < -260.0)
    ratio = (x[transition] + 275.0) / 15.0
    envelope[transition] = 0.5 - 0.5 * np.cos(math.pi * ratio)
    envelope[x > 275.0] = 0.0
    transition = (x > 260.0) & (x <= 275.0)
    ratio = (x[transition] - 260.0) / 15.0
    envelope[transition] = 0.5 + 0.5 * np.cos(math.pi * ratio)
    base *= envelope

    lateral = 1.0 + 0.08 * np.sin(
        2.0 * math.pi * y[:, np.newaxis] / WIDTH_M
    )
    heights = np.clip(lateral * base[np.newaxis, :], -AMPLITUDE_M, AMPLITUDE_M)
    slope_y, slope_x = np.gradient(
        heights,
        float(y[1] - y[0]),
        dx,
    )
    active = (x >= -260.0) & (x <= 260.0)
    return heights, {
        "length_m": LENGTH_M,
        "width_m": WIDTH_M,
        "resolution_m": dx,
        "minimum_height_m": float(np.min(heights[:, active])),
        "maximum_height_m": float(np.max(heights[:, active])),
        "rms_height_m": float(
            np.sqrt(np.mean(heights[:, active] ** 2))
        ),
        "maximum_slope_deg": float(
            np.degrees(
                np.arctan(
                    np.max(
                        np.hypot(
                            slope_x[:, active],
                            slope_y[:, active],
                        )
                    )
                )
            )
        ),
        "flat_launch_end_x_m": -275.0,
        "rough_start_x_m": -260.0,
    }


def _write_grayscale_png(path: Path, values: np.ndarray) -> None:
    image = np.asarray(np.round(values), dtype=np.uint8)
    height, width = image.shape
    scanlines = b"".join(b"\x00" + row.tobytes() for row in image)

    def chunk(kind: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + kind
            + data
            + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
        )

    payload = b"\x89PNG\r\n\x1a\n"
    payload += chunk(
        b"IHDR",
        struct.pack(">IIBBBBB", width, height, 8, 0, 0, 0, 0),
    )
    payload += chunk(b"IDAT", zlib.compress(scanlines, level=9))
    payload += chunk(b"IEND", b"")
    path.write_bytes(payload)


def generate() -> dict[str, object]:
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    heights, metrics = generate_heightfield()
    encoded = (heights / (2.0 * AMPLITUDE_M) + 0.5) * 255.0
    encoded[0, 0] = 0.0
    encoded[-1, -1] = 255.0
    _write_grayscale_png(OUTPUT_DIRECTORY / "heightfield.png", encoded)
    vertical_scale = 2.0 * AMPLITUDE_M
    vertical_offset = -vertical_scale * 128.0 / 255.0
    scene = f"""<!-- Generated by scripts/generate_high_speed_track.py. -->
<mujoco model="upkie_high_speed_rough_track">
  <include file="../four_bar/robot.xml"/>
  <visual>
    <headlight diffuse="0.8 0.8 0.8" ambient="0.4 0.4 0.4"/>
    <rgba haze="0.18 0.24 0.30 1"/>
    <global offwidth="960" offheight="540"/>
  </visual>
  <asset>
    <hfield name="high_speed_track" file="heightfield.png"
            size="300 3 {vertical_scale:.6f} 0.10"/>
    <texture type="skybox" builtin="gradient" rgb1="0.42 0.58 0.76"
             rgb2="0.05 0.06 0.08" width="512" height="3072"/>
    <texture type="2d" name="track_grid" builtin="checker" mark="edge"
             rgb1="0.55 0.44 0.24" rgb2="0.25 0.18 0.09"
             markrgb="0.95 0.88 0.62" width="512" height="512"/>
    <material name="track" texture="track_grid" texuniform="true"
              texrepeat="300 6" reflectance="0.06"/>
  </asset>
  <worldbody>
    <light pos="-5 -4 8" dir="0.3 0.2 -1" directional="true"/>
    <geom name="terrain" type="hfield" hfield="high_speed_track"
          pos="0 0 {vertical_offset:.9f}" material="track" group="3"
          friction="1.1 0.02 0.002" condim="3"/>
  </worldbody>
</mujoco>
"""
    (OUTPUT_DIRECTORY / "scene.xml").write_text(scene, encoding="utf-8")
    metadata = {
        "seed": SEED,
        "amplitude_limit_m": AMPLITUDE_M,
        "grid": {"rows": NY, "columns": NX},
        "metrics": metrics,
    }
    (OUTPUT_DIRECTORY / "metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return metadata


if __name__ == "__main__":
    print(json.dumps(generate(), indent=2))
