#!/usr/bin/env python3
"""Generate the Unitree demo Perlin patch on a MuJoCo checkerboard floor.

Matches ``AddPerlinHeighField`` in unitree_mujoco/terrain_tool:

    AddPerlinHeighField(position=[-1.5, 4.0, 0.0], size=[2.0, 1.5])

which writes a square image with

    pnoise2(x / 100, y / 100, octaves=6, persistence=0.5, lacunarity=2.0)
    pixel = (noise + 1) / 2 * 255

and places an hfield whose MuJoCo radii are ``size/2``. The official 128 px
image is upsampled 3× here so the same wrinkles render as a smooth sheet
instead of a faceted 8 cm grid. A long checkerboard plane is kept so the
100 km/h PID can still accelerate without driving onto the 2 m rug.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

if __package__:
    from scripts.perlin import unitree_perlin_image
else:
    from perlin import unitree_perlin_image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIRECTORY = ROOT / "models" / "upkie" / "high_speed"

# Official demo call uses full-size metres; MJCF stores half-extents.
PATCH_SIZE_X_M = 2.0
PATCH_SIZE_Y_M = 1.5
UNITREE_IMAGE_PX = 128
UNITREE_SMOOTH_PX = 100.0
# 3× the demo grid so high octaves shade as wrinkles, not triangles.
IMAGE_PX = UNITREE_IMAGE_PX * 3
SMOOTH_PX = UNITREE_SMOOTH_PX * (IMAGE_PX / UNITREE_IMAGE_PX)
HEIGHT_SCALE_M = 0.20
NEGATIVE_HEIGHT_M = 0.20
PERLIN_OCTAVES = 6
PERLIN_PERSISTENCE = 0.5
PERLIN_LACUNARITY = 2.0
SEED = 20260917
PATCH_POS_X_M = 0.0
PATCH_POS_Y_M = 0.0


def generate_heightfield() -> tuple[np.ndarray, dict[str, float]]:
    heights_01 = unitree_perlin_image(
        IMAGE_PX,
        IMAGE_PX,
        smooth=SMOOTH_PX,
        octaves=PERLIN_OCTAVES,
        persistence=PERLIN_PERSISTENCE,
        lacunarity=PERLIN_LACUNARITY,
        seed=SEED,
    )
    dx = PATCH_SIZE_X_M / (IMAGE_PX - 1)
    dy = PATCH_SIZE_Y_M / (IMAGE_PX - 1)
    heights_m = heights_01 * HEIGHT_SCALE_M
    slope_y, slope_x = np.gradient(heights_m, dy, dx)
    return heights_01, {
        "length_m": PATCH_SIZE_X_M,
        "width_m": PATCH_SIZE_Y_M,
        "resolution_m": dx,
        "lateral_resolution_m": dy,
        "minimum_height_m": float(np.min(heights_m)),
        "maximum_height_m": float(np.max(heights_m)),
        "rms_height_m": float(np.sqrt(np.mean(heights_m**2))),
        "maximum_slope_deg": float(
            np.degrees(np.arctan(np.max(np.hypot(slope_x, slope_y))))
        ),
        "generator": "unitree_AddPerlinHeighField",
        "perlin_smooth_px": SMOOTH_PX,
        "perlin_octaves": PERLIN_OCTAVES,
        "perlin_persistence": PERLIN_PERSISTENCE,
        "perlin_lacunarity": PERLIN_LACUNARITY,
        "height_scale_m": HEIGHT_SCALE_M,
        "grid_columns": IMAGE_PX,
        "grid_rows": IMAGE_PX,
        "patch_pos_x_m": PATCH_POS_X_M,
        "patch_pos_y_m": PATCH_POS_Y_M,
    }


def _write_grayscale_png(path: Path, values: np.ndarray) -> None:
    image = np.asarray(np.round(values), dtype=np.uint8)
    height, width = image.shape
    import struct
    import zlib

    scanlines = b"".join(b"\x00" + row.tobytes() for row in image)

    def chunk(kind: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + kind
            + data
            + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
        )

    payload = b"\x89PNG\r\n\x1a\n"
    payload += chunk(
        b"IHDR",
        struct.pack(">IIBBBBB", width, height, 8, 0, 0, 0, 0),
    )
    payload += chunk(b"IDAT", zlib.compress(scanlines, level=6))
    payload += chunk(b"IEND", b"")
    path.write_bytes(payload)


def generate() -> dict[str, object]:
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    heights_01, metrics = generate_heightfield()
    _write_grayscale_png(
        OUTPUT_DIRECTORY / "heightfield.png", heights_01 * 255.0
    )
    radius_x = PATCH_SIZE_X_M / 2.0
    radius_y = PATCH_SIZE_Y_M / 2.0
    scene = f"""<!-- Generated by scripts/generate_high_speed_track.py.
Unitree AddPerlinHeighField demo: size=[2.0, 1.5], 128 px image upsampled 3x. -->
<mujoco model="upkie_unitree_perlin_patch">
  <include file="robot.xml"/>
  <visual>
    <headlight diffuse="0.18 0.18 0.18" ambient="0.10 0.10 0.10"/>
    <rgba haze="0.15 0.25 0.35 1"/>
    <quality shadowsize="4096"/>
    <global offwidth="960" offheight="540" azimuth="145" elevation="-38"/>
  </visual>
  <asset>
    <hfield name="unitree_perlin" file="heightfield.png"
            size="{radius_x:.3f} {radius_y:.3f} {HEIGHT_SCALE_M:.6f} {NEGATIVE_HEIGHT_M:.2f}"/>
    <texture type="skybox" builtin="gradient" rgb1="0.30 0.50 0.70"
             rgb2="0.00 0.00 0.00" width="512" height="3072"/>
    <texture name="grid" type="2d" builtin="checker" mark="edge"
             rgb1="0.20 0.30 0.40" rgb2="0.10 0.20 0.30"
             markrgb="0.80 0.80 0.80" width="512" height="512"/>
    <material name="grid" texture="grid" texrepeat="1 1" texuniform="true"
              reflectance="0.05"/>
    <material name="track" rgba="0.76 0.76 0.74 1" reflectance="0"
              specular="0.18" shininess="0.06"/>
  </asset>
  <worldbody>
    <light pos="1.2 1.0 4.5" dir="-0.25 0.20 -0.95" directional="true"
           diffuse="0.95 0.94 0.90" specular="0.20 0.18 0.16"
           castshadow="true"/>
    <geom name="floor" type="plane" size="0 0 0.05" pos="0 0 0"
          material="grid" friction="1.1 0.02 0.002" condim="3"/>
    <geom name="terrain" type="hfield" hfield="unitree_perlin"
          pos="{PATCH_POS_X_M:.3f} {PATCH_POS_Y_M:.3f} 0" material="track" group="3"
          friction="1.1 0.02 0.002" condim="3"/>
  </worldbody>
</mujoco>
"""
    (OUTPUT_DIRECTORY / "scene.xml").write_text(scene, encoding="utf-8")
    metadata = {
        "seed": SEED,
        "height_scale_m": HEIGHT_SCALE_M,
        "negative_height_m": NEGATIVE_HEIGHT_M,
        "grid": {
            "rows": int(metrics["grid_rows"]),
            "columns": int(metrics["grid_columns"]),
        },
        "metrics": metrics,
        "source": (
            "unitree_mujoco/terrain_tool AddPerlinHeighField "
            "demo: size=[2.0, 1.5], image 128 px, smooth=100, "
            "octaves=6, persistence=0.5, height_scale=0.2; "
            "mesh upsampled 3x"
        ),
    }
    (OUTPUT_DIRECTORY / "metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return metadata


if __name__ == "__main__":
    print(json.dumps(generate(), indent=2))
