#!/usr/bin/env python3
"""Generate the Unitree-scale Perlin heightfield and both robot scenes."""

from __future__ import annotations

import json
import math
import struct
import zlib
from pathlib import Path

import numpy as np

if __package__:
    from scripts.perlin import unitree_perlin_meters
else:
    from perlin import unitree_perlin_meters

ROOT = Path(__file__).resolve().parents[1]
TERRAIN_DIRECTORY = ROOT / "models" / "terrain"
LENGTH_M = 48.0
WIDTH_M = 4.0
DX_M = 0.02
DY_M = 0.02
PERLIN_SMOOTH_M = 100.0 * (2.0 / 128.0)
HEIGHT_SCALE_M = 0.20
NEGATIVE_HEIGHT_M = 0.20
PERLIN_OCTAVES = 6
PERLIN_PERSISTENCE = 0.5
PERLIN_LACUNARITY = 2.0
SEED = 20260917
FLAT_END_X_M = 6.0
ROUGH_START_X_M = 10.0
CENTER_X_M = LENGTH_M / 2.0


def generate_heightfield() -> tuple[np.ndarray, dict[str, float]]:
    nx = int(round(LENGTH_M / DX_M)) + 1
    ny = int(round(WIDTH_M / DY_M)) + 1
    x = np.linspace(0.0, LENGTH_M, nx)
    y = np.linspace(-WIDTH_M / 2.0, WIDTH_M / 2.0, ny)
    dx = float(x[1] - x[0])
    dy = float(y[1] - y[0])
    grid_y, grid_x = np.meshgrid(y, x, indexing="ij")
    unitree_01 = np.clip(
        (
            unitree_perlin_meters(
                grid_x,
                grid_y,
                smooth_m=PERLIN_SMOOTH_M,
                octaves=PERLIN_OCTAVES,
                persistence=PERLIN_PERSISTENCE,
                lacunarity=PERLIN_LACUNARITY,
                seed=SEED,
            )
            + 1.0
        )
        * 0.5,
        0.0,
        1.0,
    )
    envelope = np.ones_like(x)
    envelope[x < FLAT_END_X_M] = 0.0
    blend = (x >= FLAT_END_X_M) & (x < ROUGH_START_X_M)
    ratio = (x[blend] - FLAT_END_X_M) / (ROUGH_START_X_M - FLAT_END_X_M)
    envelope[blend] = 0.5 - 0.5 * np.cos(math.pi * ratio)
    heights_01 = 0.5 + (unitree_01 - 0.5) * envelope[np.newaxis, :]
    heights_m = (heights_01 - 0.5) * HEIGHT_SCALE_M
    slope_y, slope_x = np.gradient(heights_m, dy, dx)
    active = x >= ROUGH_START_X_M
    return heights_01, {
        "length_m": LENGTH_M,
        "width_m": WIDTH_M,
        "resolution_m": dx,
        "lateral_resolution_m": dy,
        "minimum_height_m": float(np.min(heights_m[:, active])),
        "maximum_height_m": float(np.max(heights_m[:, active])),
        "rms_height_m": float(np.sqrt(np.mean(heights_m[:, active] ** 2))),
        "maximum_slope_deg": float(
            np.degrees(np.arctan(np.max(np.hypot(slope_x[:, active], slope_y[:, active]))))
        ),
        "flat_end_x_m": FLAT_END_X_M,
        "rough_start_x_m": ROUGH_START_X_M,
        "perlin_smooth_m": PERLIN_SMOOTH_M,
        "perlin_octaves": PERLIN_OCTAVES,
        "height_scale_m": HEIGHT_SCALE_M,
        "grid_columns": nx,
        "grid_rows": ny,
    }


_HEIGHTS_01: np.ndarray | None = None


def terrain_height_m(x_m: float, y_m: float) -> float:
    """Sample the Perlin strip. Mid-grey (0.5) maps to world z = 0."""

    global _HEIGHTS_01
    if _HEIGHTS_01 is None:
        _HEIGHTS_01, _ = generate_heightfield()
    heights_01 = _HEIGHTS_01
    rows, cols = heights_01.shape
    col = np.clip(x_m / LENGTH_M * (cols - 1), 0.0, cols - 1)
    row = np.clip((WIDTH_M / 2.0 - y_m) / WIDTH_M * (rows - 1), 0.0, rows - 1)
    r0, c0 = int(row), int(col)
    r1 = min(r0 + 1, rows - 1)
    c1 = min(c0 + 1, cols - 1)
    wr, wc = row - r0, col - c0
    sample = (
        heights_01[r0, c0] * (1 - wr) * (1 - wc)
        + heights_01[r0, c1] * (1 - wr) * wc
        + heights_01[r1, c0] * wr * (1 - wc)
        + heights_01[r1, c1] * wr * wc
    )
    return float((sample - 0.5) * HEIGHT_SCALE_M)


def write_grayscale_png(path: Path, values: np.ndarray) -> None:
    image = np.asarray(np.round(values), dtype=np.uint8)
    height, width = image.shape
    scanlines = b"".join(b"\x00" + row.tobytes() for row in image)

    def chunk(kind: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + kind
            + data
            + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
        )

    payload = b"\x89PNG\r\n\x1a\n"
    payload += chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 0, 0, 0, 0))
    payload += chunk(b"IDAT", zlib.compress(scanlines, level=6))
    payload += chunk(b"IEND", b"")
    path.write_bytes(payload)


def scene_xml(*, model_name: str, extra_option: str = "") -> str:
    radius_x = LENGTH_M / 2.0
    radius_y = WIDTH_M / 2.0
    vertical_offset = -HEIGHT_SCALE_M * 0.5
    option = f"  {extra_option}\n" if extra_option else ""
    return f"""<!-- Perlin heightfield scene. Generated by scripts/generate_perlin.py. -->
<mujoco model="{model_name}">
{option}  <include file="robot.xml"/>
  <visual>
    <headlight diffuse="0.18 0.18 0.18" ambient="0.10 0.10 0.10"/>
    <rgba haze="0.15 0.25 0.35 1"/>
    <quality shadowsize="2048"/>
    <global offwidth="960" offheight="540" azimuth="140" elevation="-28"/>
  </visual>
  <asset>
    <hfield name="unitree_perlin" file="../terrain/heightfield.png"
            size="{radius_x:.3f} {radius_y:.3f} {HEIGHT_SCALE_M:.6f} {NEGATIVE_HEIGHT_M:.2f}"/>
    <texture type="skybox" builtin="gradient" rgb1="0.30 0.50 0.70"
             rgb2="0.00 0.00 0.00" width="512" height="3072"/>
    <texture name="grid" type="2d" builtin="checker" mark="edge"
             rgb1="0.20 0.30 0.40" rgb2="0.10 0.20 0.30"
             markrgb="0.80 0.80 0.80" width="512" height="512"/>
    <material name="grid" texture="grid" texrepeat="1 1" texuniform="true"
              reflectance="0.05"/>
    <material name="track" rgba="0.76 0.76 0.74 1" reflectance="0"
              specular="0.18" shininess="0.06"/>
  </asset>
  <worldbody>
    <light pos="2.0 1.5 4.0" dir="-0.25 0.15 -0.95" directional="true"
           diffuse="0.95 0.94 0.90" specular="0.18 0.16 0.14"
           castshadow="true"/>
    <geom name="terrain" type="hfield" hfield="unitree_perlin"
          pos="{CENTER_X_M:.3f} 0 {vertical_offset:.6f}" material="track" group="3"
          friction="1.1 0.02 0.002" condim="3"/>
  </worldbody>
</mujoco>
"""


def generate() -> dict[str, object]:
    TERRAIN_DIRECTORY.mkdir(parents=True, exist_ok=True)
    heights_01, metrics = generate_heightfield()
    write_grayscale_png(TERRAIN_DIRECTORY / "heightfield.png", heights_01 * 255.0)
    prototype_scene = ROOT / "models" / "prototype" / "scene.xml"
    wide_scene = ROOT / "models" / "wide_car" / "scene.xml"
    prototype_scene.write_text(
        scene_xml(model_name="prototype_perlin"),
        encoding="utf-8",
    )
    wide_scene.write_text(scene_xml(model_name="wide_car_perlin"), encoding="utf-8")
    metadata = {
        "seed": SEED,
        "metrics": metrics,
        "source": (
            "Unitree AddPerlinHeighField spatial match: "
            "smooth=1.5625 m, octaves=6, height_scale=0.2 m"
        ),
        "scenes": {
            "prototype": "models/prototype/scene.xml",
            "wide_car": "models/wide_car/scene.xml",
        },
    }
    (TERRAIN_DIRECTORY / "metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return metadata


if __name__ == "__main__":
    print(json.dumps(generate(), indent=2))
